
spring.data.mongodb.uri=mongodb://localhost:27017/echomenswear


jwt.secret=your-very-secure-secret-key-at-least-32-characters


server.port=${PORT:8080}


logging.level.org.springframework.security=DEBUG
logging.level.com.echomenswear=DEBUG


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ikramshemse@gmail.com


spring.mail.password=ybtu iblz sreh ndry
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true